"""
Migración de base de datos generada por Django.

Este archivo describe los cambios estructurales que Django aplica a SQLite.
No se recomienda modificar manualmente las operaciones generadas.
"""

# Generated by Django 6.1 on 2026-09-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('CodAutor', models.AutoField(db_column='CodAutor', primary_key=True, serialize=False)),
                ('NombreAutor', models.CharField(db_column='NombreAutor', max_length=150)),
            ],
            options={
                'db_table': 'AUTOR',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('CodEditorial', models.AutoField(db_column='CodEditorial', primary_key=True, serialize=False)),
                ('NombreEditorial', models.CharField(db_column='NombreEditorial', max_length=150)),
            ],
            options={
                'db_table': 'EDITORIAL',
            },
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('CodLector', models.AutoField(db_column='CodLector', primary_key=True, serialize=False)),
                ('ApellidoP', models.CharField(db_column='ApellidoP', max_length=100)),
                ('ApellidoM', models.CharField(db_column='ApellidoM', max_length=100)),
                ('Nombres', models.CharField(db_column='Nombres', max_length=100)),
            ],
            options={
                'db_table': 'LECTOR',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('CodLibro', models.AutoField(db_column='CodLibro', primary_key=True, serialize=False)),
                ('Titulo', models.CharField(db_column='Titulo', max_length=200)),
            ],
            options={
                'db_table': 'LIBRO',
            },
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('pk', models.CompositePrimaryKey('CodLibro_id', 'CodAutor_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('CodAutor', models.ForeignKey(db_column='CodAutor', on_delete=django.db.models.deletion.CASCADE, related_name='libro_autores', to='biblioteca_app.autor')),
                ('CodLibro', models.ForeignKey(db_column='CodLibro', on_delete=django.db.models.deletion.CASCADE, related_name='libro_autores', to='biblioteca_app.libro')),
            ],
            options={
                'db_table': 'LIBRO_AUTOR',
            },
        ),
        migrations.CreateModel(
            name='LibroEditorial',
            fields=[
                ('pk', models.CompositePrimaryKey('CodLibro_id', 'CodEditorial_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('CodEditorial', models.ForeignKey(db_column='CodEditorial', on_delete=django.db.models.deletion.CASCADE, related_name='libro_editoriales', to='biblioteca_app.editorial')),
                ('CodLibro', models.ForeignKey(db_column='CodLibro', on_delete=django.db.models.deletion.CASCADE, related_name='libro_editoriales', to='biblioteca_app.libro')),
            ],
            options={
                'db_table': 'LIBRO_EDITORIAL',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('FechaDev', models.DateField(db_column='FechaDev')),
                ('pk', models.CompositePrimaryKey('CodLibro_id', 'CodLector_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('CodLector', models.ForeignKey(db_column='CodLector', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca_app.lector')),
                ('CodLibro', models.ForeignKey(db_column='CodLibro', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca_app.libro')),
            ],
            options={
                'db_table': 'PRESTAMO',
            },
        ),
    ]
