"""
Migración de base de datos generada por Django.

Este archivo describe los cambios estructurales que Django aplica a SQLite.
No se recomienda modificar manualmente las operaciones generadas.
"""

# Generated by Django 6.1 on 2026-09-02 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroautor',
            name='CodAutor',
            field=models.ForeignKey(db_column='CodAutor', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.autor'),
        ),
        migrations.AlterField(
            model_name='libroeditorial',
            name='CodEditorial',
            field=models.ForeignKey(db_column='CodEditorial', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.editorial'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUT', models.CharField(db_column='RUT', max_length=12, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('LECTOR', 'Lector'), ('ADMIN', 'Administrador')], db_column='TipoUsuario', default='LECTOR', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PERFIL_USUARIO',
            },
        ),
    ]
