"""
Migración de base de datos generada por Django.

Este archivo describe los cambios estructurales que Django aplica a SQLite.
No se recomienda modificar manualmente las operaciones generadas.
"""

# Generated by Django 6.1 on 2026-09-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_alter_libroautor_codautor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='lector',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_usuario', to='biblioteca_app.lector'),
        ),
    ]
