"""
Migración de base de datos generada por Django.

Este archivo describe los cambios estructurales que Django aplica a SQLite.
No se recomienda modificar manualmente las operaciones generadas.
"""

# Generated by Django 6.1 on 2026-09-02 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0003_perfilusuario_lector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('CodDevolucion', models.AutoField(db_column='CodDevolucion', primary_key=True, serialize=False)),
                ('FechaDevProgramada', models.DateField(db_column='FechaDevProgramada')),
                ('FechaDevolucionReal', models.DateField(db_column='FechaDevolucionReal')),
                ('DiasAtraso', models.PositiveIntegerField(db_column='DiasAtraso', default=0)),
                ('Estado', models.CharField(choices=[('A_TIEMPO', 'Devuelto a tiempo'), ('ATRASADO', 'Devuelto con atraso')], db_column='Estado', max_length=20)),
                ('CodLector', models.ForeignKey(db_column='CodLector', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='biblioteca_app.lector')),
                ('CodLibro', models.ForeignKey(db_column='CodLibro', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='biblioteca_app.libro')),
            ],
            options={
                'db_table': 'DEVOLUCION',
                'ordering': ['-FechaDevolucionReal', '-CodDevolucion'],
            },
        ),
    ]
