"""
Migración de base de datos generada por Django.

Este archivo describe los cambios estructurales que Django aplica a SQLite.
No se recomienda modificar manualmente las operaciones generadas.
"""

# Generated by Django 6.1 on 2026-09-02 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0004_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroautor',
            name='CodAutor',
            field=models.ForeignKey(db_column='CodAutor', on_delete=django.db.models.deletion.CASCADE, related_name='libro_autores', to='biblioteca_app.autor'),
        ),
        migrations.AlterField(
            model_name='libroeditorial',
            name='CodEditorial',
            field=models.ForeignKey(db_column='CodEditorial', on_delete=django.db.models.deletion.CASCADE, related_name='libro_editoriales', to='biblioteca_app.editorial'),
        ),
    ]
