"""
Migración de base de datos generada por Django.

Este archivo describe los cambios estructurales que Django aplica a SQLite.
No se recomienda modificar manualmente las operaciones generadas.
"""

# Generated by Django 6.1 on 2026-09-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0005_alter_libroautor_codautor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroautor',
            name='CodAutor',
            field=models.ForeignKey(db_column='CodAutor', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.autor'),
        ),
        migrations.AlterField(
            model_name='libroeditorial',
            name='CodEditorial',
            field=models.ForeignKey(db_column='CodEditorial', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.editorial'),
        ),
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('CodSolicitud', models.AutoField(db_column='CodSolicitud', primary_key=True, serialize=False)),
                ('FechaSolicitud', models.DateTimeField(auto_now_add=True, db_column='FechaSolicitud')),
                ('Estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada')], db_column='Estado', default='PENDIENTE', max_length=20)),
                ('FechaDevSolicitada', models.DateField(blank=True, db_column='FechaDevSolicitada', null=True)),
                ('FechaRespuesta', models.DateTimeField(blank=True, db_column='FechaRespuesta', null=True)),
                ('Observacion', models.TextField(blank=True, db_column='Observacion', default='')),
                ('CodLector', models.ForeignKey(db_column='CodLector', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_prestamo', to='biblioteca_app.lector')),
                ('CodLibro', models.ForeignKey(db_column='CodLibro', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_prestamo', to='biblioteca_app.libro')),
            ],
            options={
                'db_table': 'SOLICITUD_PRESTAMO',
                'ordering': ['-FechaSolicitud', '-CodSolicitud'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('Estado__in', ['PENDIENTE', 'APROBADA'])), fields=('CodLibro', 'CodLector'), name='solicitud_libro_lector_activa_unica')],
            },
        ),
    ]
