"""
Migración de base de datos generada por Django.

Este archivo describe los cambios estructurales que Django aplica a SQLite.
No se recomienda modificar manualmente las operaciones generadas.
"""

# Generated by Django 6.1 on 2026-09-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0006_alter_libroautor_codautor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='PortadaURL',
            field=models.URLField(blank=True, db_column='PortadaURL', default='', max_length=500),
        ),
        migrations.CreateModel(
            name='SolicitudLibro',
            fields=[
                ('CodSolicitud', models.AutoField(db_column='CodSolicitud', primary_key=True, serialize=False)),
                ('Titulo', models.CharField(db_column='Titulo', max_length=300)),
                ('Autor', models.CharField(blank=True, db_column='Autor', default='', max_length=300)),
                ('Editorial', models.CharField(blank=True, db_column='Editorial', default='', max_length=300)),
                ('Anio', models.PositiveIntegerField(blank=True, db_column='Anio', null=True)),
                ('PortadaURL', models.URLField(blank=True, db_column='PortadaURL', default='', max_length=500)),
                ('OpenLibraryKey', models.CharField(blank=True, db_column='OpenLibraryKey', default='', max_length=200)),
                ('FechaSolicitud', models.DateTimeField(auto_now_add=True, db_column='FechaSolicitud')),
                ('Estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], db_column='Estado', default='PENDIENTE', max_length=20)),
                ('FechaRespuesta', models.DateTimeField(blank=True, db_column='FechaRespuesta', null=True)),
                ('Observacion', models.TextField(blank=True, db_column='Observacion', default='')),
                ('CodLector', models.ForeignKey(db_column='CodLector', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_libros', to='biblioteca_app.lector')),
            ],
            options={
                'db_table': 'SOLICITUD_LIBRO',
                'ordering': ['-FechaSolicitud', '-CodSolicitud'],
            },
        ),
    ]
