"""
Migración de base de datos generada por Django.

Este archivo describe los cambios estructurales que Django aplica a SQLite.
No se recomienda modificar manualmente las operaciones generadas.
"""

# Generated by Django 6.1
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0008_restaurar_relaciones_autor_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='Telefono',
            field=models.CharField(blank=True, db_column='Telefono', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lector',
            name='Direccion',
            field=models.CharField(blank=True, db_column='Direccion', default='', max_length=200),
        ),
    ]
