# Generated by Django 6.1.1 on 2026-09-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0012_logactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactividad',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('REGISTRO', 'Registro de usuario'), ('2FA_CONFIGURADO', '2FA configurado'), ('2FA_VERIFICADO', '2FA verificado'), ('RECUPERACION_PASSWORD', 'Recuperación de contraseña'), ('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('PRESTAMO', 'Préstamo'), ('DEVOLUCION', 'Devolución'), ('SOLICITUD', 'Solicitud'), ('ADQUISICION', 'Adquisición de libro'), ('RECHAZO', 'Rechazo')], db_column='Accion', max_length=30),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='resultado',
            field=models.CharField(choices=[('EXITO', 'Éxito'), ('ERROR', 'Error'), ('INFO', 'Información')], db_column='Resultado', default='EXITO', max_length=10),
        ),
    ]
