"""
Django settings for biblioteca project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path

# Importa 'config' para leer valores desde variables de entorno
# o desde un archivo .env local (que NUNCA se sube a git).
from decouple import config


# ============================================================
# RUTAS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SEGURIDAD
# ============================================================

# La clave secreta ahora se lee desde la variable de entorno SECRET_KEY
# (definida en el archivo .env local, o en las variables de entorno
# del contenedor Docker en producción). Ya no queda escrita en el código.
SECRET_KEY = config('SECRET_KEY')

DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]

# ============================================================
# APLICACIONES
# ============================================================

INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'biblioteca_app',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# CONFIGURACIÓN PRINCIPAL
# ============================================================

ROOT_URLCONF = 'biblioteca.urls'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [

    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = 'biblioteca.wsgi.application'


# ============================================================
# BASE DE DATOS
# ============================================================

DATABASES = {

    'default': {

        'ENGINE':
            'django.db.backends.sqlite3',

        'NAME':
            BASE_DIR / 'db.sqlite3',
    }
}


# ============================================================
# VALIDACIÓN DE CONTRASEÑAS
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',

        'OPTIONS': {
            'min_length': 8,
        },
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

    {
        'NAME':
            'biblioteca.validators.PasswordSecurityValidator',
    },
]


# ============================================================
# IDIOMA
# ============================================================

LANGUAGE_CODE = 'es-cl'


# ============================================================
# ZONA HORARIA
# ============================================================

TIME_ZONE = 'America/Santiago'


USE_I18N = True

USE_TZ = True


# ============================================================
# ARCHIVOS ESTÁTICOS
# ============================================================

STATIC_URL = 'static/'


# ============================================================
# CORREO ELECTRÓNICO
# ============================================================

EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
)

DEFAULT_FROM_EMAIL = 'biblioteca@inacap.cl'


# ============================================================
# SEGURIDAD DE COOKIES
# ============================================================

SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_SAMESITE = 'Lax'


# ============================================================
# PROTECCIÓN CONTRA CLICKJACKING
# ============================================================

X_FRAME_OPTIONS = 'DENY'